### ISSUE TITLE
How to treat value errors in TEXT function

### ISSUE THREAD

**Issue by malankriel** [AutoActuary/excel-text#2]
When the TEXT function receives an error value as an input, it should return the same error value (as opposed to raising a runtime error). Do you agree @rudolfbyker ? What "value" should be returned?

![image](https://user-images.githubusercontent.com/51300197/136907747-77c22e13-27c6-401e-bd2a-00fd62704159.png)

The same applies for when invalid syntax is provided in the `format_text` argument of the text function:
`TEXT(123.123, "[>1000$# ##0.0")`

**Comment by rudolfbyker** [comment]
@malankriel  what was the format string when you make this example? I'm trying to convert this to doctests.
 
> ![image](https://user-images.githubusercontent.com/51300197/136907747-77c22e13-27c6-401e-bd2a-00fd62704159.png)
